site_name: WM's learning 中學物理
theme:
  name: material
  logo: assets/images/abc.png
  language: zh-TW
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://unpkg.com/d3@7/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.15.3/dist/browser/index.js
  - https://unpkg.com/markmap-view@0.15.3/dist/browser/index.js

plugins:
  - markmap:
      # disable the default assets first
      d3_version: ''
      lib_version: ''
      view_version: ''


nav:
  - 首頁: index.md
  - 光的折射: 
    - 基本概念: refraction.md
    - 練習題目: refraction_QA.md
  - 向心力:
    - 基本概念: centripetal_force/centripetal_force_outline.md
  # 其他章節...

extra_css:
  - stylesheets/extra.css